### PR TITLE
Hotfix for IconPath Issue

### PR DESCRIPTION
**Pull request by cd-tronic**
Signed-off-by: Carlo Dischler stuff@cd-tronic.de (github: cd-tronic)
Signed-off-by: cd-tronic <stuff@cd-tronic.de>

### CODE REVIEW

**Comment by cd-tronic** [comment]
fixes #139

**Comment by hoffe86** [comment]
@cd-tronic Please can you do a sign-off the commit?
Afterwards I will create a new release for the store

**Comment by cd-tronic** [comment]
Hi @hoffe86 ,

i don't know where your message has gone. I only saw the notification mail.
We talked about sign-off the last time but i thought it is enough to do it like i did? Don't know why DCO error is shown...? Do I have to to the sign-off using git commit --amend --signoff?

**Comment by hoffe86** [comment]
Hi @cd-tronic,
Not sure what the git command is exactly doing. 
Can you try to fix the review comment and do a signoff maybe this fix the issue?

**Review by cd-tronic — COMMENTED** [review]
Signed-off-by: cd-tronic <stuff@cd-tronic.de>

**Comment by cd-tronic** [comment]
Hi @hoffe86,
i miss understood DCO. SignOff needs to be added to every commit not just the PR.

**Pull request merged**
