### PR TITLE
Add AppVeyor Build

### PR DESCRIPTION
**Pull request by cniweb**
Setup AppVeyor build job #1

### CODE REVIEW

**Comment by cniweb** [comment]
@NicoVermeir is it not good?

**Comment by NicoVermeir** [comment]
@cniweb sorry haven't had the chance to check it out yet, getting hammered at work at the moment.
it looks good to me, thanks for the contribution!

**Comment by cniweb** [comment]
@NicoVermeir You must enable it for:
https://ci.appveyor.com/project/openhab/openhab-windows

**Comment by cniweb** [comment]
And you must change the badget:
https://github.com/openhab/openhab.windows/blame/master/README.md#L1
to `/openhab/openhab-windows`

**Comment by NicoVermeir** [comment]
I see, @kaikreuzer does openhab have an appveyor account already?

**Comment by cniweb** [comment]
I have an appveyor account and i activate the openhab/openhab.windows build:
https://ci.appveyor.com/project/cniweb/openhab-windows-q4jkt

**Pull request merged**
