### PR TITLE
Corrections for German translation

### PR DESCRIPTION
**Pull request by pinki**
Besides simple corrections, the spelling of OpenHAB and URL has been made consistent.

### CODE REVIEW

**Comment by hoffe86** [comment]
Hey @pinki
Thanks for your contribution.
Please could you sign-off your commits and doing the PR based on the "releases/beta" branch?

**Comment by pinki** [comment]
Hey @hoffe86,
I just signed-off the commit.
How can I change this PR to the releases/beta branch?

**Comment by hoffe86** [comment]
> Hey @hoffe86, I just signed-off the commit. How can I change this PR to the releases/beta branch?

I switched back to main and will take that the changes will go into to the beta branch, but seems the signoff is in wrong format because DCO does not accept it.

Could you change it to the following format "Signed-off-by: Author Name <authoremail@example.com>"
There is also guidance in the check tab

**Comment by NorbertHD** [comment]
The correct spelling is openHAB with a lowercase o.

**Comment by hoffe86** [comment]
Hey @pinki 
I created a new PR #210 including your changes and I will close this PR

**Pull request closed without merging**
