### PR TITLE
Signed-off-by: Timothy Clark <rebeltat@rebeldesigns.net>

### PR DESCRIPTION
**Pull request by RebelTat**

### CODE REVIEW

**Review by RebelTat — COMMENTED** [review]
Signed-off-by: Timothy Clark <rebeltat@rebeldesigns.net>

**Review by RebelTat — COMMENTED** [review]
Approved

**Comment by hoffe86** [comment]
Hey @RebelTat 
Thanks for contribution,

I have a few things we needs to be changed on your PR:
- Please remove the workflow for sonarqube, because there is already an integration in SonarQube cloud service (SonarCloud)
  See [workflows/ci.yml](https://github.com/openhab/openhab-windows/blob/main/.github/workflows/ci.yml) and [openHab Windows app @SonarCloud](https://sonarcloud.io/project/overview?id=openhab_openhab-windows)
- Remove the .vscode files
- Correct the naming from OpenHab to OpenHAB, because this is the official spelling
- Sign off your commit like explained in the DCO section the Check tab

**Comment by hoffe86** [comment]
No reaction, closing PR

**Pull request closed without merging**
