### PR TITLE
Features settings improvements

### PR DESCRIPTION
**Pull request by hoffe86**
Implemented some UI improvements for settings view and did several fixes

### CODE REVIEW

**Comment by cd-tronic** [comment]
Hi @hoffe86 did you get any feedback from @NicoVermeir regarding this project?
Glad to see some progress on this. I also started updateing some things but didn't do any commits till now. I think Nico is the only one responsive for this GIT and the Updates in MS Store but seems to be offline on this at the moment.

**Comment by hoffe86** [comment]
> Hi @hoffe86 did you get any feedback from @NicoVermeir regarding this project?
> Glad to see some progress on this. I also started updateing some things but didn't do any commits till now. I think Nico is the only one responsive for this GIT and the Updates in MS Store but seems to be offline on this at the moment.

Hey @cd-tronic 
No reaction till today.
My idea was to fixed the PR and write a message to @NicoVermeir to ask him to review the PR. Otherwise I would try to contact the other project contributors

**Comment by cd-tronic** [comment]
Sound's good! Hope you get him or one of the others!

**Comment by hoffe86** [comment]
@cd-tronic I am now contributor for the project and will merge the latest PR to master.
Is it possible that you doing a test on your side?

**Comment by cd-tronic** [comment]
Hi @hoffe86 ,

great to hear that you are an contributor now :) Sounds like this project is alive again. 

I started from scrath now and switched to VS2019. 
Looks pretty good at the moment :)

Do you know how the updateprocess to windows store will look like when a new release will be ready? Who is responsible for updating the files in windows store?

I will see when i get some time to fix a few things. Maybe we should also get rid of all the Warnings to get this project a bit cleaner.

**Comment by cd-tronic** [comment]
Hi @hoffe86 
I never worked on a public GIT project till now. Only private GITs. I wanted to push my latest commits to the repository. But got a erro message that I'm not allowed to.
I think i have to get a Contributor before i can push something right? How can I get one?
I think i also have to sign the license?

**Comment by hoffe86** [comment]
Hi @cd-tronic 
GitHub is working in the way that you are creating a fork of a repository and using pull request to bring our changes back to the source repository.

Maybe this links could be helpful:
- [Fork a repo](https://help.github.com/en/github/getting-started-with-github/fork-a-repo)
- [Creating a pull request from a fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

- [Working with GitHub Fork in Visual Studio](https://doc.fireflymigration.com/working-with-github-fork-in-visual-studio.html)

**Comment by cd-tronic** [comment]
Hi @hoffe86,

thanks for the infos. I understanded how it works before.
Have you seen my PR? 
https://github.com/openhab/openhab-windows/pull/133

I got an DCO error but i think i signed off correctly.
I did it manually by adding the "Signed-off-by:  ..." phrase. 
Do I have to use "git commit --amend --signoff" command?

**Comment by hoffe86** [comment]
Normally it should be enough to add it manually.
I using a git hook "prepare-commit-msg" to do the sign-off automatically 

```
NAME=$(git config user.name)
 EMAIL=$(git config user.email)

if [ -z "$NAME" ]; then
    echo "empty git config user.name"
    exit 1
fi

if [ -z "$EMAIL" ]; then
    echo "empty git config user.email"
    exit 1
fi

git interpret-trailers --if-exists doNothing --trailer \
    "Signed-off-by: $NAME <$EMAIL> (github: hoffe86)"  \
    --in-place "$1"
```

**Pull request merged**
