### PR TITLE
Signed-off-by: Timothy Clark rebeltat@rebeldesigns.net

### PR DESCRIPTION
**Pull request by RebelTat**
Signed-off-by: Timothy Clark rebeltat@rebeldesigns.net

### CODE REVIEW

**Review by RebelTat — COMMENTED** [review]
Signed-off-by: Timothy Clark <rebeltat@rebeldesigns.net>

**Comment by hoffe86** [comment]
@RebelTaT DCO check failed -> Comment needs to be signed off

**Review by RebelTat — COMMENTED** [review]
appears correct
Signed-off-by: Timothy Clark rebeltat@rebeldesigns.net

**Comment by cd-tronic** [comment]
@RebelTat  you need to sign-off every single commit for the DCO to pass. So add the singn-off in a new line to the two commits also.
and: looks like you changed the Name of the pullrequest to your sign-off.

**Pull request closed without merging**
